// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using personagemAPI.Model;

namespace personagemAPI.Migrations
{
    [DbContext(typeof(personagemContext))]
    [Migration("20210517232002_collum")]
    partial class collum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("personagemAPI.Model.personagem", b =>
                {
                    b.Property<int>("personagemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("caracteristicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("personagemId");

                    b.ToTable("personagens");
                });
#pragma warning restore 612, 618
        }
    }
}
